[package]
name = "oidar-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
oidar_base = {path="../oidar_base"}
easy-repl = "0.2.1"
env_logger = "0.11.5"
anyhow = "1.0.94"

url.workspace = true
log.workspace = true